Add deployment repo
byu-oit/uapi-ts pull request #6
Opened 2021-01-22 18:14 UTC by blakemorgan

Since we're suing GitHub package manager for our payment manager packages, they must be scoped with the orgs name. Since they're scoped with @byu-oit, any @byu-oit package we want to use must be in GitHub pacakges. This will deploy these types to GPM and provide a way to do it to NPM.

2021-01-22 19:34 UTC, stuft2 requested changes
I think we should have a test job that the NPM and GPM deploy steps depend on, that way don't deploy before the tests run.

2021-01-22 19:37 UTC, blakemorgan commented
@stuft2 I'm not sure I know what you mean. I put a test step in the deploy job, so wouldn't it not deploy if that fails?

2021-01-22 19:40 UTC, stuft2 commented
Sorry, I thought the NPM deploy was a separate job. As is it will work just fine. Would there be a benefit to separating them into three jobs (test, npm, gpm)?

2021-01-22 20:03 UTC, stuft2 commented
@blakemorgan We can add the NPM portion to the workflow. Just change the command from `npm publish` to `npm publish --access public` since our organization is on the free tier and we can only publish public packages.

2021-01-25 19:45 UTC, stuft2 approved these changes

2021-01-25 19:45 UTC, merged